### ISSUE TITLE
Is there an option to center the whole stars?

### ISSUE THREAD

**Issue by josephrexme** [craigh411/vue-star-rating#37]
The stars are aligned to start from left to right and that made it unfit in a layout where I have all text and images aligned center. Was able to add:
```css
.vue-star-rating{
  justify-content: center;
}
```
to center it but I want to know if there's an option for this or if it could be added. I can work on a PR
